/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GraphsSearchGlobalPostRequest
 */
export interface GraphsSearchGlobalPostRequest {
    /**
     * Search query for finding entities
     * @type {string}
     * @memberof GraphsSearchGlobalPostRequest
     */
    'query': string;
    /**
     * Maximum number of entities to return
     * @type {number}
     * @memberof GraphsSearchGlobalPostRequest
     */
    'top_k'?: number;
}

