/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GraphsHierarchyGlobalPost200ResponseEdgesInner } from './graphs-hierarchy-global-post200-response-edges-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { GraphsHierarchyGlobalPost200ResponseNodesInner } from './graphs-hierarchy-global-post200-response-nodes-inner';

/**
 * 
 * @export
 * @interface GraphsHierarchyGlobalPost200Response
 */
export interface GraphsHierarchyGlobalPost200Response {
    /**
     * List of nodes (collections, documents, entities)
     * @type {Array<GraphsHierarchyGlobalPost200ResponseNodesInner>}
     * @memberof GraphsHierarchyGlobalPost200Response
     */
    'nodes'?: Array<GraphsHierarchyGlobalPost200ResponseNodesInner>;
    /**
     * List of edges showing hierarchical relationships
     * @type {Array<GraphsHierarchyGlobalPost200ResponseEdgesInner>}
     * @memberof GraphsHierarchyGlobalPost200Response
     */
    'edges'?: Array<GraphsHierarchyGlobalPost200ResponseEdgesInner>;
}

