/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GraphsHierarchyGlobalPost200ResponseNodesInner
 */
export interface GraphsHierarchyGlobalPost200ResponseNodesInner {
    /**
     * Unique node ID (e.g., col_{id}, doc_{id}, ent_{workspace}_{id})
     * @type {string}
     * @memberof GraphsHierarchyGlobalPost200ResponseNodesInner
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof GraphsHierarchyGlobalPost200ResponseNodesInner
     */
    'type'?: GraphsHierarchyGlobalPost200ResponseNodesInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GraphsHierarchyGlobalPost200ResponseNodesInner
     */
    'name'?: string;
    /**
     * Additional metadata specific to node type
     * @type {object}
     * @memberof GraphsHierarchyGlobalPost200ResponseNodesInner
     */
    'metadata'?: object;
}

export const GraphsHierarchyGlobalPost200ResponseNodesInnerTypeEnum = {
    collection: 'collection',
    document: 'document',
    entity: 'entity'
} as const;

export type GraphsHierarchyGlobalPost200ResponseNodesInnerTypeEnum = typeof GraphsHierarchyGlobalPost200ResponseNodesInnerTypeEnum[keyof typeof GraphsHierarchyGlobalPost200ResponseNodesInnerTypeEnum];


