/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GraphsHierarchyGlobalPostRequest
 */
export interface GraphsHierarchyGlobalPostRequest {
    /**
     * Optional query to filter entities (currently unused, reserved for future)
     * @type {string}
     * @memberof GraphsHierarchyGlobalPostRequest
     */
    'query'?: string;
    /**
     * Maximum number of entities to include
     * @type {number}
     * @memberof GraphsHierarchyGlobalPostRequest
     */
    'top_k'?: number;
}

