/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GraphsSearchGlobalPost200ResponseEntitiesInner
 */
export interface GraphsSearchGlobalPost200ResponseEntitiesInner {
    /**
     * 
     * @type {string}
     * @memberof GraphsSearchGlobalPost200ResponseEntitiesInner
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof GraphsSearchGlobalPost200ResponseEntitiesInner
     */
    'entity_name'?: string;
    /**
     * Collection ID where this entity belongs
     * @type {string}
     * @memberof GraphsSearchGlobalPost200ResponseEntitiesInner
     */
    'workspace'?: string;
    /**
     * 
     * @type {string}
     * @memberof GraphsSearchGlobalPost200ResponseEntitiesInner
     */
    'content'?: string;
    /**
     * Similarity score
     * @type {number}
     * @memberof GraphsSearchGlobalPost200ResponseEntitiesInner
     */
    'distance'?: number;
}

