/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GraphsSearchGlobalPost200ResponseEntitiesInner } from './graphs-search-global-post200-response-entities-inner';

/**
 * 
 * @export
 * @interface GraphsSearchGlobalPost200Response
 */
export interface GraphsSearchGlobalPost200Response {
    /**
     * List of matched entities across all collections
     * @type {Array<GraphsSearchGlobalPost200ResponseEntitiesInner>}
     * @memberof GraphsSearchGlobalPost200Response
     */
    'entities'?: Array<GraphsSearchGlobalPost200ResponseEntitiesInner>;
    /**
     * Graph nodes for visualization
     * @type {Array<object>}
     * @memberof GraphsSearchGlobalPost200Response
     */
    'nodes'?: Array<object>;
    /**
     * Graph edges including federation links
     * @type {Array<object>}
     * @memberof GraphsSearchGlobalPost200Response
     */
    'edges'?: Array<object>;
}

