/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GraphsHierarchyGlobalPost200ResponseEdgesInner
 */
export interface GraphsHierarchyGlobalPost200ResponseEdgesInner {
    /**
     * 
     * @type {string}
     * @memberof GraphsHierarchyGlobalPost200ResponseEdgesInner
     */
    'source'?: string;
    /**
     * 
     * @type {string}
     * @memberof GraphsHierarchyGlobalPost200ResponseEdgesInner
     */
    'target'?: string;
    /**
     * 
     * @type {string}
     * @memberof GraphsHierarchyGlobalPost200ResponseEdgesInner
     */
    'type'?: GraphsHierarchyGlobalPost200ResponseEdgesInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GraphsHierarchyGlobalPost200ResponseEdgesInner
     */
    'label'?: string;
}

export const GraphsHierarchyGlobalPost200ResponseEdgesInnerTypeEnum = {
    CONTAINS: 'CONTAINS',
    EXTRACTED_FROM: 'EXTRACTED_FROM'
} as const;

export type GraphsHierarchyGlobalPost200ResponseEdgesInnerTypeEnum = typeof GraphsHierarchyGlobalPost200ResponseEdgesInnerTypeEnum[keyof typeof GraphsHierarchyGlobalPost200ResponseEdgesInnerTypeEnum];


